language: node_js
node_js:
  - "10"

dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadless lib
  - ng build lib
  - ng build --aot --prod --base-href /dm-table/ demo-app

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
