language: node_js
node_js:
  - "10"

dist: trusty
sudo: required

branches:
  only:
  - master
  - release

before_script:
  - npm install -g @angular/cli
  - npm install -g coveralls

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run build:demo

after_success:
  - npm run coverall

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/demo-app
  on:
    branch: release

deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  local_dir: dist/lib
  on:
    branch: release
