language: node_js
node_js:
  - "10"

dist: trusty
sudo: required

branches:
  only:
  - master
  - release

jobs:
  include:
    - stage: test and build
      script:
        - npm run lint
        - npm run test
        - npm run build
      before_script:
        - npm install -g @angular/cli
        - npm install -g coveralls
      after_success:
        - npm run coverall

    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        before_deploy: cd dist/lib
        on:
          branch: release

    - stage: demo-app release
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/demo-app
        on:
          branch: release
