language: node_js
node_js:
  - "10"

dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli
  - npm install -g codecov

script:
  - ng lint
  - npm test
  - ng build lib
  - ng build --aot --prod --base-href /dm-table/ demo-app

after_success:
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/demo-app
  on:
    branch: master
