name: Build and deploy Library

on:
  push:
    branches:
      - master
    paths:
      - projects/lib/package.json
      - projects/lib/package-lock.json
      - .github/workflows/build-lib.yaml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm ci
      # - name: Check the syntax
      #   run: npm run lint
      - name: Build library
        run: npm run build
      - name: Deploy lib to NPM
        run: cd /home/runner/work/ngx-dm-table/ngx-dm-table/dist/lib && npm publish --access public
        working-directory: projects/lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
